# Ref: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#automated-publishing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [
            # Commenting out as there is no clear reason why this should run on multiple OSs.
            # macos-latest,
            # windows-latest,
            ubuntu-latest,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
      - name: Publish
        if: success() &&
          startsWith( github.ref, 'refs/tags/v') &&
          matrix.os == 'ubuntu-latest'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
